### ISSUE TITLE
3.28.x NFC data field contains garbage

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#27]

**Comment by ojousima** [comment]
Fixed in refactor where NFC is under drivers.

**Comment by ojousima** [comment]
Reopening until merged to master

**Comment by DG12** [comment]
What does "fixed in refactor" mean?

**Comment by ojousima** [comment]
Refactoring means restructuring existing code without changing the functionality.

The NFC code used be under folder `tasks/ ` in ruuvi.firmware.c. The tasks are shared across almost every firmware which runs Ruuvi code, so the tasks were moved under ruuvi.drivers.c.  

This bug is fixed in ruuvi.drivers.c, but as the issue still exists in the master-branch I'll keep it open as a note to others.
